name: Node CI

on: [push, pull_request]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13
      uses: actions/setup-node@v1
      with:
        node-version: '13'
    - name: npm install, and test
      run: |
        npm install
        npm test

  update:
    needs: [test]
    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13
      uses: actions/setup-node@v1
      with:
        node-version: '13'
    - name: npm generate
      run: |
        npm install
        npm run update
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.gtoken }}
