name: Submit Branch
on:
  issues:
    types: [opened, reopened]
  push:
    branches:
      - 'submit-*'

jobs:
  pr:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 13
      uses: actions/setup-node@v1
      with:
        node-version: '13'

    - name: npm install
      run: npm install

    - name: Create Pull Request
      id: open-pr
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_label: "bot"

    - name: Enable Auto Merge
      run: node autoMerge.js
      env:
        GITHUB_TOKEN: ${{ secrets.bottoken }}
        NUMBER: ${{ steps.open-pr.outputs.pr_number }}

    - name: Close Issue
      run: node closeIssue.js
      env:
        GITHUB_TOKEN: ${{ secrets.bottoken }}
        NUMBER: ${{ steps.open-pr.outputs.pr_number }}

  publish:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 13
      uses: actions/setup-node@v1
      with:
        node-version: '13'

    - name: npm install
      run: npm install

    - name: Commit Branch
      run: node script/submitPr.js
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_BODY: ${{ github.event.issue.body }}
        GITHUB_TOKEN: ${{ secrets.gtoken }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.gtoken }}
        branch: ${{ format('submit-{0}', github.event.issue.number) }}
        force: true
