name: Submit Branch
on:
  issues:
    types: [opened, reopened]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.bottoken }}

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: npm install
      run: npm install

    - run: git pull origin master

    - name: Save Change
      run: node script/saveChange.mjs
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_BODY: ${{ github.event.issue.body }}

    - run: git checkout -b ${{ format('submit-{0}', github.event.issue.number) }}

    - name: Commit Branch
      run: node script/submitPr.js
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_BODY: ${{ github.event.issue.body }}

    - run: git push origin ${{ format('submit-{0}', github.event.issue.number) }} -f

    - name: Create Pull Request
      id: open-pr
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: ${{ format('submit-{0}', github.event.issue.number) }}
        pr_label: "bot"

    - name: Enable Auto Merge
      run: node script/autoMerge.js
      env:
        GITHUB_TOKEN: ${{ secrets.bottoken }}
        NUMBER: ${{ steps.open-pr.outputs.pr_number }}

    - name: Close Issue
      run: node script/closeIssue.js
      env:
        GITHUB_TOKEN: ${{ secrets.bottoken }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
